# use a better colorscheme
colorscheme github

set global tabstop 2
set global indentwidth 2

# use spaces instead of tabs
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'
hook global InsertChar \t %{ try %{
  execute-keys -draft h %opt{indentwidth}@
} }

# load plugins
%sh{
    autoload_directory() {
        find -L "$1" -type f -name '*\.kak' \
            -exec printf 'try %%{ source "%s" } catch %%{ echo -debug Autoload: could not load "%s" }\n' '{}' '{}' \;
    }

    #if [ -d "${kak_config}/autoload" ]; then
    #    autoload_directory ${kak_config}/autoload
    #fi

    autoload_directory ${kak_config}/plugins/kakoune-vertical-selection/
    autoload_directory ${kak_config}/plugins/kakoune-sudo-write/
}

# Setup vertical selection mappings
map -docstring "select pattern down" global user v :select-down<ret>
map -docstring "select pattern up" global user <a-v> :select-up<ret>
map -docstring "select both directions" global user V :select-vertically<ret>

